### ISSUE TITLE
Eldritch Enfeeblement Heal Never Procs

### ISSUE THREAD

**Issue by LightningFerix** [Sweenus/SimplySkills#100]
![image](https://github.com/Sweenus/SimplySkills/assets/79895448/7ae7f7c2-3f87-40e2-b8e7-e658b139cce3)

As show by this image, I have over 100% spell crit chance (UI from WizardEx: Director's Cut). I confirmed this with the dev team and 100% indicates a 1x multiplier, so only values _above_ 100% should actually be considered as increased crit chance. Regardless, I still have over 100% crit chance, not to mention a very high crit damage, that whenever I cast any spell I should regain a bunch of health every single time. However, I get zero hearts back when casting spells.

**Comment by LightningFerix** [comment]
I did some more testing and it seems that Eldritch Enfeeblement only procs on Simply Skills Path of the Wizard Signature Ability spells, NOT when spells from Spell Engine are cast using runes. Is this intended behavior? And if so, could the node descriptions be rewritten to clarify that Spell Engine spells aren't compatible with these effects, only Simply Skills Signature Ability spells?

**Comment by Sweenus** [comment]
You are correct that crit chance attribute starts at 100, so 100% = 0% in this stat screen.
According to this stat screen, you have %150 crit chance, you should be healing on spell cast.

This passive does actually work with spells casted as per normal with runes, I tested it just now with a fire wand. You may have some kind of a mod compatiblity issue.

**Comment by LightningFerix** [comment]
Ah okay so it seems maybe the reason it didn't heal me is because I had no target? When I shoot a spell _at_ something I think I get the heal, but when I shoot with no target it does not. My confusion was because Eldritch Enfeeblement says "restore health **on spell cast**" but it's actually "on spell hit"

**Comment by Sweenus** [comment]
Ah, good catch
The logic does still take place on spell cast, not spell hit. But it does require a target for it to take effect.
Admittedly, I can't quite recall why I made this limitation, but I'm pretty sure it was for a reason.
