### ISSUE TITLE
Spell Echo passive for Mage cancels multi-hit spells.

### ISSUE THREAD

**Issue by Sazuzaki** [Sweenus/SimplySkills#11]
Heyo, just wanted to say this mod is fucking cool. I really hope this mod gets completed as I'm really excited to see what you have in store for the other trees.

Back to the point, the Spell Echo passive is pretty bad if you're running Fire/Arcane due to Flame Breath and Arcane Beam. It's bad in the sense that it cancels the entire spell if Spell Echo procs due to Fire Breath's/Arcane Beam's multi-hit nature. Of course, I can just not allocate a point into Spell Echo, but it's frustrating in the sense that I have to completely reset my class progress if I fall for the trap.

It's amazing for Frost Mage though.

**Comment by Sweenus** [comment]
Hey there,

Very glad to hear you're enjoying the mod, and thank you for the kind words 🙂

I've been able to reproduce the issue you mention and totally agree that it's not ideal.
I'll see if there is a way I can fetch the information of what spell is being cast. If I can do this, I'll either disable the ability or have it behave differently, when the spell is of the channelled variety.

**Comment by Sweenus** [comment]
This should be fixed in the latest version.
Some internal changes to Spell Engine actually appear to have resolved this issue without my input 🥳
