### ISSUE TITLE
Warrior effect (Raging Javelin) causes CTD if triggered with empty hand

### ISSUE THREAD

**Issue by darkcolouredbox** [Sweenus/SimplySkills#113]
To reproduce;

Acquire [Goliath] for the (Earthshaker) effect, and [Bound] for the (Raging Javelin) effect.

Trigger (Earthshaker) by jumping from a height, near a hostile mob, while holding an item.
- This will trigger the effect as intended, no crash.

Trigger (Earthshaker) by jumping from a height, near a hostile mob, with an empty hand.
- The game will immediately crash to desktop, erroring with
> Cannot invoke " ... " because "model" is null

**Comment by Sweenus** [comment]
Thank you for the detailed report!
This is now fixed as of version 1.7.0.
