### ISSUE TITLE
[Balance] Mage Crits build is broken OP

### ISSUE THREAD

**Issue by MihanDeNoob** [Sweenus/SimplySkills#115]
Maxed out first talalnt tree (lvl42) with crits is absolutely busted, and thats ignoring the ascendant tree.
Ive been playing arcane mage and dealing insane amount damage, one-two shoting hardest mobs dungeon arise can offer.
Boss fights (be it data pack mobs or new bosses from mods or revorked vanilla bosses) were a cakewalk since damage was so insane.

I was dealing around 75 dmg with the arcane crits build (and that ignoring the special ability and beam ability), with almost every spell cast being a crit. I was wearing full arcane robe set and arcane staff (not netherite), with only staff having the enchant (level 3 increased spell dmg)

All that combing with mods like [RpgDifficulty](https://www.curseforge.com/minecraft/mc-mods/rpgdifficulty) or/and [Dungeon Difficulty [Fabric]](https://www.curseforge.com/minecraft/mc-mods/dungeon-difficulty) and [Majrusz's Progressive Difficulty](https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty)

The problem is how high critical damage and crit chances can be boosted in the first tree with big talents.
 I think the best solution is to reduce the amount of crit chance boost you can get from the talant trees (including ascendant tree) but keep the very high crit damage, to keep that Gambling feeling and up the satisfaction when you actually get that crit and deal huge dmg and one shot mobs.

**Comment by Sweenus** [comment]
Hello,
Couple of things to address here:

- When you say 75 damage, do you mean 75 dps on a target dummy? This is not overpowered in the scope of this mod
- The crit chance gain from the tree is actually very very minimal. The majority of the crit chance you have is from the enchants on your gear (seriously, you can almost hit crit chance cap just with enchants alone).
The only exception to this is the 'Overload' talent, which needs to be built around to actually be able to use it effectively

In general, I'd recommend enabling DAS and/or DDR in the general config and tweaking the values to suit your balance needs.

**Comment by MihanDeNoob** [comment]
oh no, the dps is twice as that if not more when combing other skills and talents. I think its the Overload talent that needs to be tuned down then. 

What is the DAS and DDR in the config? Also what is the crit chance cap and where can i get more info about stuff? Like, does Spellbraker affects vanilla projectiles (fire balls, wither skulls) or only from this mod?

**Comment by MihanDeNoob** [comment]
???
