### ISSUE TITLE
Crusader Consecration Issue

### ISSUE THREAD

**Issue by ELCuleroPingon** [Sweenus/SimplySkills#14]
Hi and thanks for the awesome mod.

Currently playing on a private modded 1.20.1 server and consecration damages my buddies rather than healing them. What’s the issue here? 

My assumption is they’re flagged as enemies by default.

**Comment by Sweenus** [comment]
Hi there, glad you're enjoying it!

Unfortunately, to my knowledge, Minecraft does not have a native way to handle friendly fire in a granular way.
This means you either need to have PvP disabled on your server (or be using a pvp toggle mod) in order for beneficial effects to work on your friends.

I hope this answers your question 🙂

**Comment by ELCuleroPingon** [comment]
Yeah that fixed it thanks
