### ISSUE TITLE
1.20.1 Server ticking entity crash

### ISSUE THREAD

**Issue by FuturisticDruid** [Sweenus/SimplySkills#15]
Server crashed after player killed a magister from the Spellblades and such mod and then went near a portal from the mod.
crashlog says something about simply skills and spell engine
[crash-2023-10-15_02.00.49-server (1).txt](https://github.com/Sweenus/SimplySkills/files/12908554/crash-2023-10-15_02.00.49-server.1.txt)

**Comment by Sweenus** [comment]
Can you give me information about the players specialisations?
Screenshot all the relevant skill trees for me if you're able.

**Comment by FuturisticDruid** [comment]
I can as soon as the player comes back online. don't know when that will be.

edit: nevermind as soon as we restart the server it crashes again with no one on
same crash

**Comment by Sweenus** [comment]
I've not been able to reproduce the issue, but I've pushed a possible fix live in version 0.22.5.
Please update and let me know if you run into any further issues 🙂

**Comment by Sweenus** [comment]
Hello 👋
Have you had any further issue with this?

**Comment by FuturisticDruid** [comment]
No it seems to have fixed the issue

**Comment by Sweenus** [comment]
That's great to hear - thank you for letting me know 🙂
