### ISSUE TITLE
Bugged skill tree

### ISSUE THREAD

**Issue by Mewknight101** [Sweenus/SimplySkills#16]
Having an issue where after using a skill chronical, I can no longer get more than 42 usable skill points.
I tried the manuscript and using commands to reset my level and skill trees and it resets me to 0 but I cant receive more than 42 points
![Base Profile Screenshot 2023 10 18 - 13 37 15 53](https://github.com/Sweenus/SimplySkills/assets/148315779/056604e4-11d4-43df-abaf-4a3d35522658)

**Comment by Sweenus** [comment]
This isn't a bug. A level cap of 42 was introduced for the base tree a few updates ago.

**Comment by Mewknight101** [comment]
Oh ok, I had assumed it was a bug due to the earned points displaying on the top right. Thankyou for clarifying things
