### ISSUE TITLE
[Display-Bug]Chinese Translation display issues in skill tree only.

### ISSUE THREAD

**Issue by White-Biggy** [Sweenus/SimplySkills#18]
> I have created a zh_cn.json for this mod,
- I do only translate the skill's name and their effect discriptions, and 3 books' item name and the display texts.
- I find out:
   1.the skill tree skills and their effect discriptions won't be able to display any chinese texts even for reloading the game.
   2.I have upload the file and hope you could help me to find out why, hoping the file could help to the localizaion.
   3.I didn't translate the config text because I think it doesn't require to translate and also it will add unstabilities if someone to change it.

- [ ] [zh_cn.json](https://github.com/Sweenus/SimplySkills/files/13221725/zh_cn.json)

**Comment by Sweenus** [comment]
For anyone else who reads this - translations currently must be done via datapack.
For an example of how this can be done, take a look at White-Biggy's fantastic work, here: https://github.com/White-Biggy/DataPack-Chinese-SimplySkills
