### ISSUE TITLE
Crash on terrain generation with this and Combat roll

### ISSUE THREAD

**Issue by FedUpWizard** [Sweenus/SimplySkills#22]
[crash-2023-11-10_21.22.03-client.txt](https://github.com/Sweenus/SimplySkills/files/13322447/crash-2023-11-10_21.22.03-client.txt)

I installed this mod, but my game crashed on finishing terrain generation. I then checked the crash log and found it was Combat Roll:
https://www.curseforge.com/minecraft/mc-mods/combat-roll 

When I removed it the game generated normally and loaded in.

**Comment by Sweenus** [comment]
There's nothing in this log that is Simply Skills related. This should probably be reported on the Combat Roll issue tracker.

**Comment by FedUpWizard** [comment]
Thank you, will do ;)

**Comment by FedUpWizard** [comment]
> This seems to only happen when QKL/ Fabric Language Kotlin is installed.
> ### Logs:
> 
>     * Simply Skills + Combat Roll (No QKL): https://mclo.gs/TeeWt5A
> 
>     * Simply Skills + Combat Roll + QKL: https://mclo.gs/A9220T1 (**Crashed**)
> 
>     * Simply Skills + Combat Roll + Fabric Language Kotlin : https://mclo.gs/kFzw0U0 (**Crashed**)
> 
>     * Combat Roll + QKL : https://mclo.gs/2I76WEa (NO Simply Skills!)
> 
> 
> ### Error message:
> 
> ```
> [11:25:48] [Render thread/ERROR]: Unreported exception thrown!
> java.lang.IllegalArgumentException: Can't find attribute combatroll:count
> 	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.combatroll.api.EntityAttributes_CombatRoll.getAttributeValue(EntityAttributes_CombatRoll.java:52) ~[transformed-mod-combatroll.i0:0/:?]
> 	at net.combatroll.client.RollManager.tick(RollManager.java:55) ~[transformed-mod-combatroll.i0:0/:?]
> 	at net.minecraft.class_310.tryRolling(class_310.java:3560) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_310.handler$zpa000$combatroll$tick_TAIL(class_310.java:3552) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_310.method_1574(class_310.java:1957) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
> 	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.21.2.jar:?]
> 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.21.2.jar:?]
> 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.21.2.jar:?]
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
> ```

This was found by one of the combat roll devs called Aninuscsalas. It seems the issue lies with the Fabric Kotlin Libraries/ QKL. Funnily enough I don't need the libraries to begin with so just wanted to let you know incase someone else has the same problem.
