### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by parheli** [Sweenus/SimplySkills#23]
Not sure if i should ask you or the author of the Paladins mod, but how do I make paladin's ability "Consecration' count another player as an ally, for it to heal them and not damage?

**Comment by Sweenus** [comment]
Hello, you are asking in the correct place 🙂 
Simply Skills uses vanilla teams for its friendly fire logic. To heal other players, you need to ensure you are in the same team (or just disable server PvP if it is not needed).
/team add [teamname]
/team join [teamname]
