### ISSUE TITLE
How do you make spellbooks and use the Spellbinder?

### ISSUE THREAD

**Issue by moonfly71** [Sweenus/SimplySkills#24]
So, the mod doesn't seem to actually have any spells in it? the specializations have some abilities, and the ranger gets elemental arrows, but no other spells. It doesn't seem to allow for any actual spells to be made at the spellbinder even if we have a full bookshelf. Do we need another sperate mod to add spells and spellbooks in? Are there no spells in the base mode of Simply Skills?

**Comment by Sweenus** [comment]
To fully interact with the Spell Binding Table and spell casting, you should install the RPG series mods (Wizards, Paladins & Priests, Archers). The only spells in Simply Skills are the signature abilities from specialisations, of which you can only have one.
