### ISSUE TITLE
The mod is not compatible with 1.20

### ISSUE THREAD

**Issue by RellinQuill** [Sweenus/SimplySkills#26]
When installed alongside Minecraft 1.20 using Modrinth it does not launch, saying that 1.20 is incompatible with this mod. The image of the fabric window is pinned below alongside the text of the error. Modrinth didn't load Spell Power by default as well, but that is probably because the mod isn't on there yet
![image](https://github.com/Sweenus/SimplySkills/assets/152077691/b2f27e77-77b6-449e-b258-92f069e66696)
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install spell_power, version 0.9.13+1.20.1 or later.
	 - Replace mod 'SimplySkills' (simplyskills) 0.25.3+1.20.1 with any version that is compatible with:
		 - minecraft 1.20
		 - spell_engine 0.9.26+1.20.1
More details:
	 - Mod 'SimplySkills' (simplyskills) 0.25.3+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'SimplySkills' (simplyskills) 0.25.3+1.20.1 requires version 0.9.16+1.20.1 or later of spell_power, which is missing!
	 - Mod 'SimplySkills' (simplyskills) 0.25.3+1.20.1 requires any version between 0.12.0+1.20.1 (inclusive) and 0.13.0+1.20.1 (exclusive) of mod 'Spell Engine' (spell_engine), but only the wrong version is present: 0.9.26+1.20.1!
	 - Mod 'Spell Engine' (spell_engine) 0.9.26+1.20.1 requires version 0.9.13+1.20.1 or later of spell_power, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Sweenus** [comment]
Hi there,

It looks like I've locked the version unintentionally. I'll fix it in the next update.
