### ISSUE TITLE
Suggestion: add effect descriptions

### ISSUE THREAD

**Issue by Partonetrain** [Sweenus/SimplySkills#28]
Simply add this lang key to add support for mods like Just Enough Effect Descriptions.
![image](https://github.com/Sweenus/SimplySkills/assets/19861808/ee189956-3655-4711-82f1-afc0ac02f7e9)

**Comment by Sweenus** [comment]
Effect descriptions already exist, as seen in the lang file: https://github.com/Sweenus/SimplySkills/blob/1.20.1/src/main/resources/assets/simplyskills/lang/en_us.json

If you're playing on the 1.19.2 version, this is very outdated and might be missing these.

**Comment by Partonetrain** [comment]
I'm playing on 1.20.1. It seems EMIffect ignores the ".desc" lang keys. I will create a bug report there. My apologies.
