### ISSUE TITLE
[Request] A forge port?

### ISSUE THREAD

**Issue by lera2od** [Sweenus/SimplySkills#33]
this is an awesome mod and I want to put it in my modpack but it is a fabric mod. Are you guys planning to port it to forge?

**Comment by CanecaKun** [comment]
There is a solution and it worked wonderfully for me. 
Download all mods mentioned on the curseforge page of simply skills and its dependencies for fabric, and download these mods as well as their dependencies:

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
https://www.curseforge.com/minecraft/mc-mods/connector-extras
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

I´m running on forge with other forge mods and everything worked fine so far.
(except for a minor visual bug i reported here but thats another story ;) )

**Comment by Sweenus** [comment]
> There is a solution and it worked wonderfully for me. Download all mods mentioned on the curseforge page of simply skills and its dependencies for fabric, and download these mods as well as their dependencies:
> 
> https://www.curseforge.com/minecraft/mc-mods/sinytra-connector https://www.curseforge.com/minecraft/mc-mods/connector-extras https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api
> 
> I´m running on forge with other forge mods and everything worked fine so far. (except for a minor visual bug i reported here but thats another story ;) )

This is the way 🙂 
Simply Skills can't be ported to Forge because it has Fabric-only dependencies, but Sinytra Connector is here to save us all!
