### ISSUE TITLE
Lvl cap

### ISSUE THREAD

**Issue by LaiderPT** [Sweenus/SimplySkills#34]
Hello, me and my friends we made a server and we have Simply Skills, and we noticed that the lvl of the main tree is capped at lvl 42 and we were undering if there was a way to increase the max lvl or to even remove the cap, we tried o look on the mod config but we couldn't find anything about it

**Comment by Simiux** [comment]
@LaiderPT  I have made a datapack in which you can edit the cap, just update the category.json in the data folder and drop it into your world folder under datapack.

Right now it's set to 95 points, as 1 branch takes around 54 points, and with 95 you can do a bit under 2 trees, for a dual job kinda situation.

![image](https://github.com/Sweenus/SimplySkills/assets/152472414/d55db482-ea44-45d0-bddc-a4e085a10db7)

[SimplySkills SP.zip](https://github.com/Sweenus/SimplySkills/files/13612872/SimplySkills.SP.zip)

**Comment by LaiderPT** [comment]
Thank you so much for the time taken to make this for all the help and for the fast answer :)
By the way to allow multiple jobs it's just need to change the exclusive_root to false right ?

**Comment by wakandaforeva123** [comment]
Hello, I was trying to implement the datapack but it seems nothing I have done changes the level cap to my desired specs. If you are willing could you explain further how to install it? For context, this mod is part of a modpack, no clue if that has any effect on the matter, I have tried placing it in the datapack folder and/or the config folder to no avail. I am also confused by "update the category.json file". Update it to my specs, update a different file in the configs??

**Comment by Epicminerrrrr** [comment]
Hi I made a server using the Fantasy MC Fabric 1.20.1 and I was wondering how I would uncap the skill tree and I don't have anything named category.json. I was wondering how I would change it?

**Comment by Simiux** [comment]
> Thank you so much for the time taken to make this for all the help and for the fast answer :) By the way to allow multiple jobs it's just need to change the exclusive_root to false right ?

I have not tested this, but in theory should be possible :)

**Comment by Simiux** [comment]
> Hello, I was trying to implement the datapack but it seems nothing I have done changes the level cap to my desired specs. If you are willing could you explain further how to install it? For context, this mod is part of a modpack, no clue if that has any effect on the matter, I have tried placing it in the datapack folder and/or the config folder to no avail. I am also confused by "update the category.json file". Update it to my specs, update a different file in the configs??

Simply drop the zip file as is in the desired world you'd like it to load.
I for example have my world as Alaen Uram so you follow this directory
"D:\Minecraft\saves\Alaen Uram\datapacks" or wherever your MC is saved as long as it's in the datapack of the desired world.

Make sure you're playing on 1.20 as this datapack was made for this version. If you have another version you need to change the info in the "pack.mcmeta" file. 

To make changes enter the ZIP file and open all the folders until you get to category.json, open that with TXT editor and change spent point limits.

Update to my specs just means specifications, so basically your wishes, I have it set to 95, you can set it to 999999 if you like, this works and I've tested it.

But most likely your issue lies within the versions, let me know :)

**Comment by Simiux** [comment]
> Hi I made a server using the Fantasy MC Fabric 1.20.1 and I was wondering how I would uncap the skill tree and I don't have anything named category.json. I was wondering how I would change it?

The only way to uncap it so far is to write a ridiculously high number, there are around 350~ skills so putting it to 400-500 is actually enough to unlock everything.

Fantasy MC fabric does not come with the Simply Skills mod, so you'd have to add that, and also download the datapack zip file I have provided above and add it to your server world. Inside the zip file if you open all the folders you will see category.json, you should be able to edit that with txt editor windows and change to your liking.

**Comment by Sweenus** [comment]
While it's possible to raise the levelcap via datapack, the base tree in Simply Skills is limited by design and I wouldn't suggest raising it.
Version 1.1.0 has added the Ascendancy skill tree which is uncapped and allows for long-term end-game progression. I hope this feature meets your needs!
