### ISSUE TITLE
Skill not compatible with certain modded weapons.

### ISSUE THREAD

**Issue by BystanderA** [Sweenus/SimplySkills#35]
Ranger arrow rain will not be triggered when using bows from More Bows: Restrung.
Also, it doesn't work will with vivecraft realistic bow aim, because with VR, player doesn't aim with cross hair. Not sure what would be the best way to fix it, I am personally considering if the arrow rain instead of fly towards where the cross hair is pointing, if there is a regular arrow shoots out first as leading arrow, with rest arrows fly towards where the leading arrow lands.
How ever, this is a beautiful mod, my friends and me are enjoying it very much, thank you for making it.

**Comment by Sweenus** [comment]
Hi there, I am glad you're enjoying the mod!

Unfortunately, there's nothing I can do to fix the ranger abilities not working with certain modded bows. This is because they are overriding and replacing the vanilla bow's methods. This means that my mixin is entirely skipped 😞
