### ISSUE TITLE
Is there a way to add mobs to the Blacklist for Skills?

### ISSUE THREAD

**Issue by IvorAmlug** [Sweenus/SimplySkills#39]
Everytime i use my Bladestorm skill all creatures including horses etc just die.
I wonder if there is an Option to remove/add specific mods to the blacklist of creatures to target.

**Comment by Sweenus** [comment]
There's no config option like this, but the mods does take pets, villagers & friendly players into consideration.
I would think that a tamed horse would fall under this category though. Does this still occur on the latest version of the mod?
