### ISSUE TITLE
How can I reset the skills?

### ISSUE THREAD

**Issue by Mimikyu1337** [Sweenus/SimplySkills#41]
By mistake I chose a skill tree but I wanted to go to another and I don't know how to prescribe the skills.

Try the command /puffish_skills skills reset (player) (category) but I don't know what the ID or Category of the Mod is.

It would be very helpful to me and thank you sweenuss.

**Comment by HEWSTARBUCK** [comment]
![Capture](https://github.com/Sweenus/SimplySkills/assets/157297938/bd05e1cc-0386-4d35-8df1-5d8f8308bf66)
How to reset everything

**Comment by Sboubs** [comment]
If you use puffish skills with simply skills, you need to use a "Malevolent Manuscript"

**Comment by Sweenus** [comment]
> If you use puffish skills with simply skills, you need to use a "Malevolent Manuscript"

This is correct
