### ISSUE TITLE
[Crash] Crash with 0.11.0 Pufferfish's Skills

### ISSUE THREAD

**Issue by LeoDemitori** [Sweenus/SimplySkills#45]
Crash game with 0.11.0 Pufferfish's Skills

Crash report
[simplyskills.txt](https://github.com/Sweenus/SimplySkills/files/13822745/simplyskills.txt)

**Versions:**

- Fabric Loader Version: **0.14.24**
- MC Version: **1.20.1**
- Mod Version: 1.0.0
- Fabric API Version (if present) : 0.91.0

**Comment by This1Potato** [comment]
Same problem here. Was just about to publish it myself

**Comment by chasria** [comment]
Just had the same problem. At least im not the only one

**Comment by tjeezus** [comment]
Same here, the older compatible version of pufferfish (1.10) is for an older minecraft version (1.18) so it doesn't match.

**Comment by This1Potato** [comment]
> Same here, the older compatible version of pufferfish (1.10) is for an older minecraft version (1.18) so it doesn't match.

Try with [this one](https://modrinth.com/mod/skills/version/VwEQfSf8), it's the 1.20.1 for 0.10.0 pufferfish skills (fabric)

**Comment by tjeezus** [comment]
> > Same here, the older compatible version of pufferfish (1.10) is for an older minecraft version (1.18) so it doesn't match.
> 
> Try with [this one](https://modrinth.com/mod/skills/version/VwEQfSf8), it's the 1.20.1 for 0.10.0 pufferfish skills (fabric)

This worked, thank u

**Comment by Sweenus** [comment]
As This1Potato says, just use Puffish Skills 0.10.0 for now. I'll update Simply Skills to work with the newest version when I have time.

**Comment by hiimrickross** [comment]
can confirm it seems that downgrading to 0.10.0 fabric version -- even when using forge/sinytra connector, it works.

I initially tried latest simply skills and latest puffish skills, but i was crashing on minecraft loading instantly, and it was actually saying something about xaerosmap null crash. But it wasn't xaerosmap at all, when I removed simplyskills (and kept latest puffish) it would go back to working like normal. Now im using simplyskills & puffish (0.10.0 as suggested here) and im back in my world playing OK.

But there seems to be some critical fixes in later puffish versions like memory crashes/leaks etc. Which sucks... I hope its not a problem.

**Comment by giogimic** [comment]
> As This1Potato says, just use Puffish Skills 0.10.0 for now. I'll update Simply Skills to work with the newest version when I have time.

ill blow you a kiss if you find that time soon!

**Comment by Sweenus** [comment]
@giogimic I'll take that kiss now!
Simply Skills has been updated to the latest versions of its dependencies in version 1.0.1.
