### ISSUE TITLE
Only one skill tree appearing instead of all three for specific people in a server

### ISSUE THREAD

**Issue by sedatedsadness** [Sweenus/SimplySkills#47]
one person in the server has all three skill trees and can use them but for some reason two of us only have one tab

**Comment by Partonetrain** [comment]
You could set "disableDefaultPuffishTrees": to `false` in the config and delete puffish_skills.dat. see https://github.com/Sweenus/SimplySkills/issues/46

**Comment by Sweenus** [comment]
Hi there, Simply Skills removes the default Puffish Skills trees on launch.
To get them back you will need to reenable the default puffish trees via the general config in Simply Skills.
After that, you will need to unlock the trees again with these chat commands:
/puffish_skills category unlock playername puffish_skills:mining
/puffish_skills category unlock playername puffish_skills:combat
