### ISSUE TITLE
how to reset skill everything? (please help meT^T)

### ISSUE THREAD

**Issue by HEWSTARBUCK** [Sweenus/SimplySkills#48]
![Capture](https://github.com/Sweenus/SimplySkills/assets/157297938/6d0325bc-895d-4cc0-a1d0-94e524b0f549)
how to reset skill everything 
/puffish_skills skills reset <name> <what is category for reset all>

**Comment by Sboubs** [comment]
If you use puffish skills with simply skills, you need to use a "Malevolent Manuscript"

**Comment by Sweenus** [comment]
> If you use puffish skills with simply skills, you need to use a "Malevolent Manuscript"

This is correct. The Malevolent Manuscript item is used for this purpose
