### ISSUE TITLE
How to get default Pufferfish Mining skill tree back?

### ISSUE THREAD

**Issue by aceb20** [Sweenus/SimplySkills#49]
I love the combat skill tree change, but I really liked the original pufferfish mining tree. I looked through the mod and couldn't find anywhere that had you disable that tree. How do you re-enable it?

**Comment by Sweenus** [comment]
Hi there,
You will need to reenable the defaul puffish trees via the general config in Simply Skills.
After that, you will need to unlock the trees again with these chat commands:
`/puffish_skills category unlock playername puffish_skills:mining`
`/puffish_skills category unlock playername puffish_skills:combat`

**Comment by Maxxc12** [comment]
Hello i found this while searching for a question i had myself. Is there anyway to enable just one of the base skill trees from puffish skills? For example if i wanna use just the mining tree from puffish together with the simply skills trees? Is there anyway to do that easily throught the config?
