### ISSUE TITLE
adding this mod to game causing Xaero's Map to crash on loading (seemingly resolved, is due to latest ver of puff skills?)

### ISSUE THREAD

**Issue by hiimrickross** [Sweenus/SimplySkills#50]
https://pastebin.com/ypbz5ZXy

every time I try to load the game after adding this simply skills .jar the game fails to load and complains something about xaeromap null. I've tried this with pufferfish skills fabric or forge (sinytra connector modpack environment) because its fine to use just those, but whenever simply skills is included it crashes.

--edit
I found the thread from 3 weeks back where a user says the latest version of Puffish Skills causes this mod to crash. I used their 0.10.0 link in the thread, and now it works. The XaerosMap crash seemed to be a red herring that Minecraft just landed on every time? Im not sure.

**Comment by hiimrickross** [comment]
hi also sorry to bother you but how do i access the skills seen in the trailer for the mod? specifically things like arrow rain and whatnot? i appear to have the full skill tree but i am missing the tree on the left of your picture: https://i.imgur.com/Bz8tlux.png
i only have the main big tree, not this smaller golden tree with all the special skills. do you need the amethyst imbuement mod? Additionally the config settings like "enable choosing specializations without restriction" dont seem to apply even after restarting.

FWIW: using this mod on forge environment via sinytra connector. player animation & simply swords are forge version. rest are fabric.

**Comment by Sweenus** [comment]
Sorry for the delay!
Simply Skills now supports the latest version of Puffish Skills.
To access the additional trees seen in the trailer, you need to unlock a specialisation node on the skill tree. You can only have one specialisation at a time by default.
