### ISSUE TITLE
question

### ISSUE THREAD

**Issue by elilmao** [Sweenus/SimplySkills#52]
is it possible for me to unlock different skills with commands even though they are locked?

**Comment by Sweenus** [comment]
It is possible using the commands on the Puffish Skills page: https://www.curseforge.com/minecraft/mc-mods/puffish-skills
You will need to find the skill IDs in the data files though: https://github.com/Sweenus/SimplySkills/tree/1.20.1/src/main/resources/data/simplyskills/puffish_skills/categories
