### ISSUE TITLE
How do I get spells?

### ISSUE THREAD

**Issue by LizardGod15** [Sweenus/SimplySkills#53]

**Comment by CanecaKun** [comment]
I think I have the same confusion so let me maybe clarify:

The skill-tree talks about increasing spell critical chance, critical damage, bonus to spells and other related stuff, but how exactly does one cast spells?

I thought it was about passive habilities that dealt damage like the falling sword from the berserker path but it is very confusing.

Is another mod necessary for applying those effects? Could you maybe list the compatible mods?

Thanks!

**Comment by CanecaKun** [comment]
I searched for a bit and i discovered that the paladin mod's spells mentioned on the curseforge page work with the attribute bonuses, and i think it also works with elemental arrows from the marksman class, however i still would like to find out if other mods are compatible with this, or if a new compatibility could be developed like with "Mystic" spells for example

**Comment by Sweenus** [comment]
Some signature abilities count as spells, namely priest/wizard/spellblade abilities.
If you want to cast spells in a more general sense, it is recommended to use the Wizards mod.

Simply Skills is designed around the RPG Series mods, and I'd highly recommend you use them with Simply Skills. These are:
Wizards, Paladins & Priests, and Archers.
