### ISSUE TITLE
Visual Bug when stacking "Quickfire"

### ISSUE THREAD

**Issue by CanecaKun** [Sweenus/SimplySkills#54]
![imagem_2024-02-15_200255031](https://github.com/Sweenus/SimplySkills/assets/62015531/3fb89ee1-29b7-4d19-b2ee-05868a3087f8)

I don´t know if this issue is known, however, let me state that i´m using a mod that ports fabric mods for forge with the help of the mods connector, connector extras and fabric api
Modpack listed below:
![imagem_2024-02-15_200537193](https://github.com/Sweenus/SimplySkills/assets/62015531/4a261865-7f98-413f-a71a-83cb85db182a)

The connector mods creates other .jar files to map the variables i presume, but that folder won´t help much to track the issue (if it is an issue)

**Comment by CanecaKun** [comment]
Updating with the "adaptor" mods i downloaded:

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
https://www.curseforge.com/minecraft/mc-mods/connector-extras
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

**Comment by Sweenus** [comment]
This is a duplicate, please see: https://github.com/Sweenus/SimplySkills/issues/27
