### ISSUE TITLE
Berserking does not give buffs when hitting ender dragon.

### ISSUE THREAD

**Issue by Sazuzaki** [Sweenus/SimplySkills#57]
Title

**Comment by Sweenus** [comment]
There's probably nothing I can do about that.
Iirc Ender Dragon is actually several entities in one, and not a standard mob.

**Comment by Sazuzaki** [comment]
Gotcha, yeah that's a shame then. I noticed it's also a big problem with Spell Engine, so hopefully that can get sorted out sometime. Sucks that the final boss breaks a lot of combat mechanics due to being an amalgamation of entities.
