### ISSUE TITLE
items do not stack

### ISSUE THREAD

**Issue by everfreeze** [Sweenus/SimplySkills#6]
while creating a modpack with a few mods i found a weird glitch that makes it that items dont stack. Theres no special things i did or items i used. I just started mining blocks like in normal minecraft. As i searched for the error i found the fault at this mod, i also tried if it was due to some anti-compability with other mods. But the error was still there after restarting the game with only simple skills (+needed required mods to run simple skills). Hopefully you can fix this and keep up your great work its an amazing mod :)

**Comment by Sweenus** [comment]
Hi there,

I think you've identified the wrong mod.
I can't reproduce this issue & Simply Skills doesn't interact with item stacking behavior in any way.

If you're sure it's Simply Skills, please create an entirely new Minecraft instance with only Simply Skills and its dependencies installed. Then send me a video of the issue ocurring and the latest.log. Thank you

**Comment by everfreeze** [comment]
https://drive.google.com/file/d/1diQBBFwZsABrEcWQwBolqjf6y2rFWwkd/view?usp=sharing

At the end i also included the mod list ive used for the recreation, also sorry for the link i couldnt get the video below the 10 mb.

**Comment by Sweenus** [comment]
Thank you for sending that video!
I've been able to reproduce the issue with the help of this clip. I think I know what the cause might be.
Will take a look today 🙂

**Comment by Sweenus** [comment]
I have identified the cause of the issue and deployed a fix. This will be live in the next update.
Thank you for bringing this to my attention!

**Comment by everfreeze** [comment]
Well i take the thanks and give it right back :) thankyou for providing us with ya mod its pretty nice :)

**Comment by Sweenus** [comment]
Thank you for the kind words!
The latest release containing the fix has just been published to CurseForge 🙂
