### ISSUE TITLE
[Suggestion] Unreasonable numerical design

### ISSUE THREAD

**Issue by Karashok-Leo** [Sweenus/SimplySkills#61]
https://github.com/Sweenus/SimplySkills/blob/eb2f0b402eed73b246d8a15a9ef4449fa7daadb0/src/main/java/net/sweenus/simplyskills/effects/OverloadEffect.java#L54
Are u serious?
Why not calculate the damage based on the current health instead of the max health?
I was wondering why I just killed myself...

**Comment by Sweenus** [comment]
This is intended. The ability provides a significant damage increase with the trade off of needing to juggle this mechanic. You are not intended to survive the self damage without a significant investment in defences.

**Comment by Karashok-Leo** [comment]
This punishment is too severe. At least you should provide detailed numerical values in the description text, otherwise players will only regret choosing. And the damage type here is magic damage, which is not something armor can resist. Players either use commands to withdraw their choices, or have to stop after casting four consecutive spells. A well-designed skill tree should not make players make regretful choices.

**Comment by Sweenus** [comment]
I disagree entirely. The punishment is correct.
If you want to be able to cast spells in succession, you do not take that passive.
If you want to deal burst damage with spell casts but have downtime between casts, then you do take the passive.

The skill tree requires forethought. I do not see expecting users to have critical thinking skills to be bad design.
See any complex skill tree from games such as Path of Exile, or Last Epoch for comparison.

The Malevolent Manuscript item allows users to reset their skill tree. Commands are not needed.
