### ISSUE TITLE
Speed 3 not working when under stealth effect

### ISSUE THREAD

**Issue by Fruitive** [Sweenus/SimplySkills#62]
When i use the Preparation ability with rogue, i do get the speed 3 effect, but it doesnt do anything. As soon as i dont have the stealth effect speed 3 works properly again.
Same thing happens if you use the Stealth and Speed ability in the general skill tree.
I tested this with only the required mods installed.

**Comment by Sweenus** [comment]
It does work, it's just being partially counteracted by Stealth's innate 40% movespeed reduction.
