### ISSUE TITLE
Skill Chronicle doesn't save level

### ISSUE THREAD

**Issue by dberghoff** [Sweenus/SimplySkills#67]
I saved a build using the skill chronicle and upon reapplying the build, the level was reset. This makes gaining skill points easy again and breaks progression for that build.

**Comment by Sweenus** [comment]
I am aware of this issue and have reported it to Puffish Skills, as this is achieved via their API. I am not sure that they intend to change how this works however.

**Comment by Sweenus** [comment]
It looks like additional API functions may have been added actually. I will look into this next update.
For context: https://github.com/pufmat/skillsmod/issues/54

**Comment by dberghoff** [comment]
Awesome! Is there any way to manually set my level in the meantime, or would that require the new functions?

**Comment by Sweenus** [comment]
I think you would need to set your points back to 0 and then add experience until you reach the level you were supposed to be at. This can be done via commands: https://puffish.net/skillsmod/docs/players/commands

**Comment by Sweenus** [comment]
Okay, it may have taken me a century, but this is fixed as of version 1.7.0
