### ISSUE TITLE
morebows Incompatibility 

### ISSUE THREAD

**Issue by creeloper27** [Sweenus/SimplySkills#68]
Abilities do not work when arrows are show using one of [morebows](https://modrinth.com/mod/more-bows-restrung) bows.

**Comment by Sweenus** [comment]
Hi there,
Some of the ranger bow abilities inherently do not work with modded bows that override the vanilla 'Use' method.
I recommend using a compatible bow mod, such as Archers: https://www.curseforge.com/minecraft/mc-mods/archers
