### ISSUE TITLE
[feature suggestion] tree max levels configuration

### ISSUE THREAD

**Issue by gaggara** [Sweenus/SimplySkills#70]
ability to manage max level of default upgrades tree via config files

**Comment by Sweenus** [comment]
This is not possible. The level cap is set in the data files loaded by Puffish Skills.
It's only possible to adjust the levelcap via datapack, and I would not suggest doing so as the skill tree is designed and balanced around the existing level cap. The Ascendancy skill tree was added in the most recent update with the aim to provide long-term player progression.
