### ISSUE TITLE
Extra hearts don't regenerate 

### ISSUE THREAD

**Issue by DarianStardust** [Sweenus/SimplySkills#72]
Edit: This issue is only happening with a specific Origin for me (Terram Draconis from Even more Origins), it has potion effects cut in half,  no Hp regen (which I disabled) and Hunger/thirst goes down quicker, this doesn't seem to happen with other origins even, just this one

specifically the 10% HP boosts, when regenerating health with food, the vanilla hearts heal, but the extra hearts don't, or for some reason only the very first heart regenerates Half a heart, and then stops

I can still fill those hearts with Healing items, just not hunger/saturation

**Comment by Sweenus** [comment]
In Minecraft, a heart represets 2HP. If you have a less base HP than the default of 20, it's possible for a stat boost of 10% to result in an entire heart being rendered on the HUD but only being able to be filled to half. This is because you are gaining less than the 2HP required to fill an entire heart. This is normal behaviour.

**Comment by DarianStardust** [comment]
> In Minecraft, a heart represets 2HP. If you have a less base HP than the default of 20, it's possible for a stat boost of 10% to result in an entire heart being rendered on the HUD but only being able to be filled to half. This is because you are gaining less than the 2HP required to fill an entire heart. This is normal behaviour.

I managed to find a solution, I deleted. my Origins config file, regenerated it opening the game, closed, and Disabled the "No Regen" negative ability again, now I can regen the extra hearts just fine.
 the mod had rebalanced the origin and updated, but I guess the regen config didn't work properly(?) idk, sorry for the wrong issue, but leave it in case someone else plays Terram draconis too in future
