### ISSUE TITLE
i update from 1.0.0 to the latest version  result crash to desktop

### ISSUE THREAD

**Issue by DragonlordRozza** [Sweenus/SimplySkills#74]
it loads normal and after selcet singleplayer and load a singleplayer world and when ist almost finished it crashes to the desktop i dont no why. is this cuase by an other mod?
[crash-2024-04-06_21.00.10-server.txt](https://github.com/Sweenus/SimplySkills/files/14894706/crash-2024-04-06_21.00.10-server.txt)
[crash-2024-04-06_21.00.38-client.txt](https://github.com/Sweenus/SimplySkills/files/14894708/crash-2024-04-06_21.00.38-client.txt)

**Comment by Sweenus** [comment]
This appears to be a Spellblade Next crash. Try removing that mod. If it resolves the issue, it might be best to report this on the Spellblade Next issue tracker
