### ISSUE TITLE
Ascendancy Tree Fire Damage instead of Arcane 

### ISSUE THREAD

**Issue by Food-dude-99** [Sweenus/SimplySkills#77]
Hello I am on the latest version of the mod on minecraft version 1.20.1 and I noticed on the ascendancy tree next to the Arcane Slash ability the spell damage is fire? Based on the color of the icons I'm assuming its suppose to be arcane, considering there is no other arcane spell damage in the tree and all other spell damage is present. 
![Capture](https://github.com/Sweenus/SimplySkills/assets/152713993/71265b8a-c5ce-4ef6-a91e-a145075053c0)

**Comment by Sweenus** [comment]
Thanks for the report!
Fixed in the latest version.
