### ISSUE TITLE
A way to customize the values in the skill tree

### ISSUE THREAD

**Issue by duarm** [Sweenus/SimplySkills#84]
I have some ideas on how to balance SimplySkills for my modpack. It would be nice there was a way to tune the values in the skill tree through config files, since things can get quite OP. Particularly I would like to decrease the Max HP% nodes since my tank managed to get 200 hearts by stacking flat hp (we are still dying to DAS).

Old pic (before gems)

![image](https://github.com/Sweenus/SimplySkills/assets/26150581/53a1dbd6-c5b3-40d4-9151-a8b134812357)

**Comment by Partonetrain** [comment]
Can't you do this with datapacks? See puffish skills docs

**Comment by duarm** [comment]
I think I can,  I was able to find each node inside data/simplyskills/puffish_skills/categories/tree, just trying to figure out how to edit those values via a datapack

**Comment by Sweenus** [comment]
Hey 👋 
As you've already mentioned, creating a datapack to modify the values will work. You will just need to crosscheck it against new version of the mod, whenever you choose to update.
