### ISSUE TITLE
Not working with puffish attributes 0.1

### ISSUE THREAD

**Issue by duarm** [Sweenus/SimplySkills#87]
Updated my modpack to puffish skills 0.12.1 from 0.11.6, together with latest SimplySkills, I'm getting duplicated Ranged Damage, the first one works, every ranged weapon and the armor from RPG Archers mod modifies the first entry, but every node from simplySkills adds onto the second Ranged Damage, which doesn't do anything

![image](https://github.com/Sweenus/SimplySkills/assets/26150581/fd4e9f9b-c057-4019-a927-28f1d931ae4b)

The base was originally set to NaN, but while experimenting with it, I changed to 0

**Comment by Sweenus** [comment]
Archers recently added their own ranged damage attribute via a new dependency.
Simply Skills continues to increase the ranged damage attribute from Pufferfish Skill's. These attributes work fine together.

I have tested using a target dummy, and the ranged damage from the skill tree is working correctly, even with Archers installed.
The issue in your screenshot may just be a display bug with whatever mod is displaying your attributes (Pufferfish's Skills did recently split their attributes out into a seperate mod, so such a bug would not surprise me).

**Comment by duarm** [comment]
I think the bug is a little deeper, something happened with the crossbows in my modpack. I'll investigate the cause and close this one for the time being. Thanks for the help
