### ISSUE TITLE
Crusader Unique Abilities are non-functional

### ISSUE THREAD

**Issue by AngelTechnic** [Sweenus/SimplySkills#9]
Using beta 0.18.0 on minecraft 1.20.1
Heavensmith's Call, Sacred Onslaught, and Consecration do nothing if activated, and have no cooldown.

**Comment by Sweenus** [comment]
Do you have the Paladins and Priests mod installed?
This is required to use the Crusader specialisation.

**Comment by AngelTechnic** [comment]
Yes I do, version 0.9.8

**Comment by Sweenus** [comment]
Would you mind uploading your latest log?
And can you tell me what method you used to unlock the specialisation tree?

This is not something I've been able to reproduce, so I'm not sure why you're experiencing this issue.

**Comment by AngelTechnic** [comment]
i'm using the /puffish_skills points add command to unlock the category from the tree and then to actually get points for the crusader category itself.

i'll have to generate a new log while trying one of these abilities

**Comment by Sweenus** [comment]
No need for the log actually - I've reproduced the issue.

It stems from unlocking the specialisation via commands.
For now, I'd suggest either using the Gracious & Malevolent Manuscripts for unlocking specialisations for testing, or unlocking them manually.

**Comment by Sweenus** [comment]
Welp...... think I found the issue 🤦‍♂️
![Screenshot 2023-08-15 105351](https://github.com/Sweenus/SimplySkills/assets/48658188/7432eba9-45e1-4818-8f67-ffdd4202efca)

Thank you for bringing this to my attention. I'll deploy a fix shortly.

**Comment by Sweenus** [comment]
Fix is now live on CurseForge, version 0.18.1. Thank you for your report 🙂
