### ISSUE TITLE
Level point cap adjustment.

### ISSUE THREAD

**Issue by Dragonracer1973** [Sweenus/SimplySkills#93]
Love this mod, but was curious if there is a way to blow the level cap wide open, to basically gain all the attribute points, in all three classes?

**Comment by Sweenus** [comment]
Hi there, I'm afraid short of a datapack this is not possible.
I would suggest using the versions made from Minecraft 1.20.1, as this version has an ascendancy skill tree that unlocks at max level and provides further attribute points.

**Comment by HiruTwo** [comment]
Did you manage to find a solution to this? @Dragonracer1973

**Comment by Dragonracer1973** [comment]
Sorry no. Not exactly a programer, so not sure.

**Comment by HiruTwo** [comment]
@Dragonracer1973 I found a data pack to unlock the talent tree points, I don't know if it will help you
