### ISSUE TITLE
RPG Series Compatibility - Spell Engine 1.5+ breaks SimplySkills

### ISSUE THREAD

**Issue by VitaminJake** [Sweenus/SimplySkills#98]
I use SimplySkills with all ZsoltMolnarr's RPG series mods and love them together. However, they break and no longer work alongside each other as of his update to Spell Engine 1.5.4, which is required for all latest releases of RPG series.

**Comment by GonKiIlua** [comment]
+1, simply skills cannot be used with new RPG series mod update

**Comment by TOAOB-Lake** [comment]
Just downgrade to the version that you were using before and pray that SimplySkills gets updated soon

**Comment by Taira00o** [comment]
same here, i have tried for more than 5 hours. (the old versions also no longer work) i hope it gets fixed soon :c

**Comment by Sweenus** [comment]
Resolved as of version 1.5.0

**Comment by Taira00o** [comment]
nope doesn't work

**Comment by Sweenus** [comment]
> nope doesn't work

The latest release of Simply Skills does work with the latest version of Spell Engine. If you are still having issues, it's something else. Please share your crash log.
